from nodes import ProgramNode, AndNode, CompareNode, FactNode


class StaticAnalyzer:
    def __init__(self, program: ProgramNode, state_variables: set, state_hechos: set):
        self.program = program
        self.state_variables = state_variables
        self.state_hechos = state_hechos

    def analizar(self):
        self.detectar_conflictos()
        self.detectar_redundancias()
        self.detectar_inactivas()

    def detectar_conflictos(self):
        # First, compute which rules are part of a redundant group
        redundant_rules = set()
        vistas_check = {}
        for regla in self.program.rules:
            clave = (self._cond_key(regla.condition), regla.action.id)
            if clave not in vistas_check:
                vistas_check[clave] = []
            vistas_check[clave].append(regla.name)
        for clave, reglas in vistas_check.items():
            if len(reglas) > 1:
                redundant_rules.update(reglas)

        # Report conflict only when rules are NOT redundant (different conditions, same action)
        acciones = {}
        for regla in self.program.rules:
            if regla.name not in redundant_rules:
                accion = regla.action.id
                if accion not in acciones:
                    acciones[accion] = []
                acciones[accion].append(regla.name)

        for accion, reglas in acciones.items():
            if len(reglas) > 1:
                print(f"Action {accion} generated by {', '.join(reglas)}")

    def detectar_redundancias(self):
        vistas = {}
        for regla in self.program.rules:
            clave = (self._cond_key(regla.condition), regla.action.id)
            if clave not in vistas:
                vistas[clave] = []
            vistas[clave].append(regla.name)

        for clave, reglas in vistas.items():
            if len(reglas) > 1:
                print(f"Redundant rules: {', '.join(reglas)}")

    def detectar_inactivas(self):
        # Compute which facts are potentially reachable:
        # a fact is reachable if it's an initial fact or an action of a rule
        # whose condition could possibly be satisfied
        reachable = set(self.state_hechos)
        changed = True
        while changed:
            changed = False
            for regla in self.program.rules:
                if regla.action.id not in reachable:
                    if self._condicion_satisfacible(regla.condition, reachable):
                        reachable.add(regla.action.id)
                        changed = True

        for regla in self.program.rules:
            if not self._condicion_satisfacible(regla.condition, reachable):
                print(f"Potentially inactive rule: {regla.name}")

    def _condicion_satisfacible(self, nodo, reachable_facts) -> bool:
        """Returns True if the condition could possibly be True given the state."""
        if isinstance(nodo, CompareNode):
            # If the variable is not in the state, we can't evaluate → assume satisfiable
            if nodo.id not in self.state_variables:
                return True
            val = self.state_variables[nodo.id]
            if nodo.op == ">": return val > nodo.value
            if nodo.op == "<": return val < nodo.value
            if nodo.op == "=": return val == nodo.value
            return True
        if isinstance(nodo, FactNode):
            return nodo.id in reachable_facts
        if isinstance(nodo, AndNode):
            return (self._condicion_satisfacible(nodo.left, reachable_facts) and
                    self._condicion_satisfacible(nodo.right, reachable_facts))
        return True

    def _cond_key(self, nodo) -> tuple:
        if isinstance(nodo, CompareNode):
            return ("cmp", nodo.id, nodo.op, nodo.value)
        if isinstance(nodo, FactNode):
            return ("fact", nodo.id)
        if isinstance(nodo, AndNode):
            return ("and", self._cond_key(nodo.left), self._cond_key(nodo.right))
        return ()